### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by itatsu-works** [itatsu-works/furima-31138#10]
- 自身のフリマアプリのURL
https://furima-31138.herokuapp.com/

- Basic認証のIDとパスワード
-- ID:admin
-- Password:2222

- 出品者用のメールアドレスとパスワード
-- メールアドレス:yamada@gmail.com
-- パスワード:123abc

- 購入者用のメールアドレスとパスワード
-- メールアドレス:sato@gmail.com
-- パスワード:123abc

- 購入用カードの番号・期限・セキュリティコード
-- カード番号:4242424242424242
-- 有効期限:24年12月
-- セキュリティーコード:123

**Comment by tech-oa** [comment]
itatsu-works さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○出品者はURLを直接入力して購入ページに遷移しようとすると、トップページに遷移する。
→購入ページに遷移してしまいます。

○エラーハンドリングができていること（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させる）
→誤ったクレジットカード番号を入力した際、エラー文は表示されているのですが、「Token can't be blank」というエラーが表示されています。修正をお願いいたします。


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by itatsu-works** [comment]
[修正箇所]
○出品者はURLを直接入力して購入ページに遷移しようとすると、トップページに遷移する。
→購入ページに遷移してしまいます。

○エラーハンドリングができていること（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させる）
→誤ったクレジットカード番号を入力した際、エラー文は表示されているのですが、「Token can't be blank」というエラーが表示されています。修正をお願いいたします。

**Comment by rumaruma0408** [comment]
itatsu-worksさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
